# Generated by Django 5.1.4 on 2025-01-08 18:10

import rmodel.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unicode_character",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[rmodel.models.validate_unicode],
                    ),
                ),
            ],
        ),
    ]
